# command line: main_student.py recognition -c config/ntu_rgbd/xview/student_test.yaml

base_lr: 0.01
batch_size: 256
config: config/ntu_rgbd/xview/student_test.yaml
debug: false
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeder.feeder_multimodal_ntu.Feeder
fix_teacher: true
ignore_weights: []
log_interval: 100
model: net.student_ntu.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    num_class: 60
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 5
save_log: true
save_result: true
show_topk:
- 1
skeleton_bones_pkl: ./work_dir/tmp
skeleton_joints_pkl: ./trained_models/teacher_result_ntu_xview.pkl
start_epoch: 0
step: []
teacher_weights: ./trained_models/teacher_ntu_xview.pt
test_batch_size: 64
test_feeder_args:
    data_path: /media/bruce/2Tssd1/data/ntu-rgbd-st-gcn/xview/val_data.npy
    label_path: /media/bruce/2Tssd1/data/ntu-rgbd-st-gcn/xview/val_label.pkl
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: ./trained_models/student_ntu_xview.pt
work_dir: ./work_dir/ntu_rgbd/xview/student
