work_dir: ./work_dir/pku_mmd/xview/student

skeleton_joints_pkl: ./trained_models/pku_xview_teacher.pkl

# feeder
feeder: feeder.feeder_multimodal_pku.Feeder
train_feeder_args:
  debug: False
  random_choose: False
  centralization: False
  random_move: False
  window_size: -1
  random_flip: False
  random_interval: True
  data_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/train_data.npy
  label_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/train_label.pkl
test_feeder_args:
  debug: False
  centralization: False
  evaluation: True
  data_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/val_data.npy
  label_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/val_label.pkl

# model
model: net.student.Model
model_args:
  in_channels: 3
  num_class: 51
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# training
fix_teacher: True
teacher_weights: ./trained_models/pku_xview_teacher.pt
device: [0,1,2,3]
batch_size: 64
test_batch_size: 64
weight_decay: 0.0001 #0.0001
base_lr: 0.1
step: [10, 50]
num_epoch: 80

# debug
debug: False
