work_dir: ./work_dir/pku_mmd/xview/teacher

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  debug: False
  centralization: False
  random_move: False
  data_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/train_data.npy
  label_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/train_label.pkl
test_feeder_args:
  centralization: False
  data_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/val_data.npy
  label_path: /media/bruce/2Tssd/data/pku_st_gcn/xview/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 51
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

#optim
weight_decay: 0.0001
base_lr: 0.1
step: [10, 50]

# training
device: [0,1,2,3]
batch_size: 64
test_batch_size: 64
num_epoch: 80
