# python main_student.py recognition -c config/ntu_rgbd/xsub/student_test.yaml

work_dir: ./work_dir/ntu_rgbd/xsub/student
weights: ./trained_models/student_ntu_xsub.pt

# for ensemble
skeleton_joints_pkl: ./trained_models/teacher_result_ntu_xsub.pkl

# feeder
feeder: feeder.feeder_multimodal_ntu.Feeder
test_feeder_args:
  data_path: /media/bruce/2Tssd/data/ntu-rgbd-st-gcn/xsub/val_data.npy
  label_path: /media/bruce/2Tssd/data/ntu-rgbd-st-gcn/xsub/val_label.pkl

# model
model: net.student_ntu.Model
model_args:
  in_channels: 3
  num_class: 60
  dropout: 0.5
  edge_importance_weighting: True
  graph_args:
    layout: 'ntu-rgb+d'
    strategy: 'spatial'

# test
fix_teacher: True
teacher_weights: ./trained_models/teacher_ntu_xsub.pt
phase: test
device: [0,1,2,3]
test_batch_size: 64

save_result: True
