# command line: main_teacher.py recognition -c config/ntu_rgbd/xview/teacher_test.yaml

base_lr: 0.01
batch_size: 256
config: config/ntu_rgbd/xview/teacher_test.yaml
debug: false
device:
- 0
- 1
- 2
- 3
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.st_gcn.Model
model_args:
    dropout: 0.5
    edge_importance_weighting: true
    graph_args:
        layout: ntu-rgb+d
        strategy: spatial
    in_channels: 3
    num_class: 60
nesterov: true
num_epoch: 80
num_worker: 4
optimizer: SGD
pavi_log: false
phase: test
print_log: true
save_interval: 5
save_log: true
save_result: false
show_topk:
- 1
- 5
skeleton_bones_pkl: ./work_dir/tmp
skeleton_joints_pkl: ./work_dir/tmp
start_epoch: 0
step: []
test_batch_size: 64
test_feeder_args:
    data_path: /media/bruce/2Tssd1/data/ntu-rgbd-st-gcn/xview/val_data.npy
    label_path: /media/bruce/2Tssd1/data/ntu-rgbd-st-gcn/xview/val_label.pkl
train_feeder_args: {}
use_gpu: true
weight_decay: 0.0001
weights: /media/bruce/2T/data/st-gcn/models/yansijie/st_gcn.ntu-xview.pt
work_dir: ./work_dir/ntu_rgbd/xview/teacher
